---
- name: Setup workstation
  hosts: localhost
  connection: localhost
  become: true

  pre_tasks:
    - name: Update repositories
      when: ansible_os_family == "Debian"
      ansible.builtin.apt:
        update_cache: true
      changed_when: false

  tasks:
    - name: Include base role
      ansible.builtin.include_role:
        name: packages

    - name: Include sudoers role
      ansible.builtin.include_role:
        name: sudoers
