---
- name: Setup workstation
  hosts: localhost
  connection: localhost
  become: true

  tasks:
    - name: Install packages
      ansible.builtin.apt:
        name:
          - git
          # - code
          - fzf
          - wmctrl
          - python3
          - brave-browser
          - google-chrome
          - flameshot
          - htop
          - tmux
          - npm
          - xdotool
#
# snap spotify
# virtualbox ?
# nvm
