---
- name: Add GPG keys
  ansible.builtin.apt_key:
    url: "{{ item.key.url }}"
    state: "{{ item.key.state | default('present') }}"
  loop: "{{ packages_packages | selectattr('key', 'defined') | list }}"

- name: Add repositories
  ansible.builtin.apt_repository:
    repo: "{{ item.repository.repo }}"
    state: "{{ item.repository.state | default('present') }}"
    filename: "{{ item.repository.filename | default(omit) }}"
  loop: "{{ packages_packages | selectattr('repository', 'defined') | list }}"

- name: Update package cache
  ansible.builtin.apt:
    update_cache: true

- name: Install packages
  ansible.builtin.apt:
    name: "{{ packages_packages | map(attribute='name') | list }}"
#
# snap spotify
# virtualbox ?
# nvm
