- name: Add GPG keys
  ansible.builtin.apt_key:
    url: "{{ item.url }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ base_packages.key }}"

- name: Add repositories
  ansible.builtin.apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state | default('present') }}"
    filename: "{{ item.filename | default(omit) }}"
  loop: "{{ base_packages.repository }}"

- name: Update package cache
  ansible.builtin.apt:
    update_cache: true

- name: Install packages
  ansible.builtin.apt:
    name: "{{ base_packages.name }}"
#
# snap spotify
# virtualbox ?
# nvm
